import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { CheckCircle2, Zap, X, AlertTriangle, Loader2, Info } from 'lucide-react';
import type { ForecastModel, SkipReason, SkippedCohort } from '../types/forecast';
import { SKIP_REASON_KEY } from '../types/forecast';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface ForecastParams {
  preHorizonUncertainty: number;
  postHorizonExpansionRate: number;
  confidenceHorizon: number;
  forecastLength: number;
}

interface CohortLabel {
  segment: string;
  product: string;
  channel: string;
  scenario: string;
}

export interface BulkGenerateModalProps {
  /** Controls visibility */
  isOpen: boolean;
  /** Fired when the modal should close (cancel or Done) */
  onClose: () => void;
  /** The combination that was just explicitly generated by the user */
  sourceCohort: CohortLabel | null;
  /** Total count of dim-combinations that currently have no forecast */
  missingCount: number;
  /** HW parameters that will be used for all generated forecasts */
  params: ForecastParams;
  /** Currently selected forecast model — shown as the "use for all" option */
  currentModel: ForecastModel;
  /** Live progress from App.tsx — current / total cohorts processed so far */
  generationProgress?: { current: number; total: number };
  /**
   * Called when the user confirms.  Runs bulk generation and resolves with:
   *   generated — forecasts successfully written
   *   failed    — combos skipped due to insufficient data
   */
  onConfirm: (opts: { name: string; comment: string; autoModel: boolean; autoConfidence: boolean }) => Promise<{ generated: number; failed: number; skipped: SkippedCohort[] }>;
  /**
   * A run that ALREADY happened, to be shown straight in the completion panel.
   *
   * Step 1's aggregate generate-missing does its own scoped run and then has
   * something to report - counts, skipped leaves, and the retirement statement.
   * Before this it had nowhere to report it: the completion panel is reachable
   * only by confirming a run from inside this modal, so a user who generated
   * from Step 1 never saw a coverage statement about what they had just done.
   *
   * When present the modal opens at 'complete' with this summary and never
   * shows the confirm step - there is nothing to confirm, the work is done.
   */
  initialSummary?: { generated: number; failed: number; skipped: SkippedCohort[];
    /** 'leaves' when a scoped Step 1 run reports itself: generated counts
     *  forecast LEAVES, and `failed` names the same leaves `skipped` does. */
    grain?: 'series' | 'leaves' } | null;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

type Phase = 'confirm' | 'generating' | 'complete';

/** Above this many cohorts the run is a whole-dataset job rather than a top-up,
  * and the modal says so before the confirm. Generating one cohort reduces the
  * outstanding count by exactly one, so a user who has generated a handful still
  * sees essentially the full number here -- which is the point: the offer is the
  * same size whichever path raised it. Measured on the shipped fixtures: 7,736
  * cohorts on the trimmed file and 31,856 on the full tariff file from cold. */
const SCALE_WARN_THRESHOLD = 500;

export function BulkGenerateModal({
  isOpen,
  onClose,
  sourceCohort,
  missingCount,
  params,
  currentModel,
  generationProgress,
  onConfirm,
  initialSummary = null,
}: BulkGenerateModalProps) {
  const { t } = useTranslation();
  const [phase, setPhase] = useState<Phase>(initialSummary ? 'complete' : 'confirm');
  const [summary, setSummary] = useState<{ generated: number; failed: number; skipped: SkippedCohort[]; grain?: 'series' | 'leaves' } | null>(initialSummary);
  const [runName, setRunName] = useState('');
  const [runComment, setRunComment] = useState('');
  const [autoModel, setAutoModel] = useState(true);
  const [autoConfidence, setAutoConfidence] = useState(true);

  // ABOVE the early return, deliberately. `if (!isOpen) return null` is a
  // conditional return, so a hook below it renders a different number of hooks
  // on the closed and open passes - the shape guard-trap 7 exists for.
  //
  // Why it is needed at all: this component stays mounted while closed, so
  // useState's initialiser runs once and a SECOND finished run would arrive
  // with the first run's summary still in state. Sync on the prop instead.
  React.useEffect(() => {
    if (initialSummary) { setSummary(initialSummary); setPhase('complete'); }
  }, [initialSummary]);

  if (!isOpen) return null;

  // Reset when re-opened
  const handleClose = () => {
    // Back to whichever phase this instance opens at, not blindly 'confirm':
    // a report-only open has nothing to confirm.
    setPhase(initialSummary ? 'complete' : 'confirm');
    setSummary(initialSummary);
    setRunName('');
    setRunComment('');
    setAutoModel(true);
    setAutoConfidence(true);
    onClose();
  };

  const handleConfirm = async () => {
    setPhase('generating');
    try {
      const result = await onConfirm({ name: runName.trim(), comment: runComment.trim(), autoModel, autoConfidence });
      setSummary(result);
      setPhase('complete');
    } catch {
      setPhase('complete');
      setSummary({ generated: 0, failed: missingCount, skipped: [] });
    }
  };

  // Cohort label string
  const cohortStr = sourceCohort
    ? [sourceCohort.segment, sourceCohort.product, sourceCohort.channel]
        .filter(v => v && v !== 'All')
        .join(' · ') || 'All cohorts'
    : null;

  return (
    /* Backdrop */
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={phase === 'generating' ? undefined : handleClose} />

      {/* Modal card */}
      <div className="relative w-full max-w-lg mx-4 bg-white rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">

        {/* ── Phase: Confirm ── */}
        {phase === 'confirm' && (
          <>
            {/* Header */}
            <div className="flex items-start justify-between px-6 pt-6 pb-4 shrink-0">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-[#e60000]/10 flex items-center justify-center shrink-0">
                  <Zap size={20} className="text-[#e60000]" />
                </div>
                <div>
                  <h2 className="text-base font-bold text-slate-900">{t('bulk_apply_to_all_remaining_combinations')}</h2>
                  <p className="text-xs text-slate-500 mt-0.5">
                    {missingCount} combination{missingCount !== 1 ? 's' : ''} {missingCount !== 1 ? t('bulk_don_t') : t('bulk_doesn_t')} {t('bulk_have_a_forecast_yet')}
                  </p>
                </div>
              </div>
              <button onClick={handleClose} className="text-slate-400 hover:text-slate-600 transition-colors p-1">
                <X size={18} />
              </button>
            </div>

            {/* Scrollable body */}
            <div className="flex-1 overflow-y-auto">

            {/* Source cohort pill. The prompt can now be raised as a standing
                action (Overall Forecast → Generate Missing) with no cohort
                just generated, so the no-source state is explicit rather than
                an absent element: claiming a stale "just generated X" would be
                worse than saying nothing, and rendering nothing leaves a gap. */}
            <div className="px-6 pb-3">
              <div className="bg-slate-50 rounded-lg px-4 py-2.5 text-xs flex items-center gap-2">
                {cohortStr ? (
                  <>
                    <span className="text-slate-400">{t('bulk_just_generated')}</span>
                    <span className="font-semibold text-slate-700">{cohortStr}</span>
                    <span className="text-slate-400 ml-1">· {sourceCohort?.scenario}</span>
                  </>
                ) : (
                  <span className="text-slate-500">{t('bulk_no_source_cohort')}</span>
                )}
              </div>
            </div>

            {/* Scale warning. Shown on EVERY entry path, not just the new
                'All'-state one. generateAllMissingForecasts is never passed
                cohortIds from this modal, so every route offers the same
                whole-dataset job -- the post-generation path already offered
                tens of thousands of cohorts unqualified, and fixing the trigger
                without this would have left that unchanged and merely more
                reachable. missingCount is the real number in all cases. */}
            {missingCount >= SCALE_WARN_THRESHOLD && (
              <div className="px-6 pb-3">
                {/* Matches the established amber alert in ForecastVsActualsTab
                    ("No actuals data found") on the parts that carry the
                    convention: icon size 18, amber-500 icon, text-sm
                    font-semibold amber-900 title with mb-1, text-xs amber-700
                    leading-relaxed detail, gap-3. Container keeps rounded-lg
                    px-4 py-3 to sit with the modal's own blocks -- that alert is
                    page-level at rounded-xl p-5, which would read as pasted-in
                    next to the source pill directly above this. */}
                <div className="bg-amber-50 border border-amber-200 rounded-lg px-4 py-3 flex items-start gap-3">
                  <AlertTriangle size={18} className="text-amber-500 shrink-0 mt-0.5" />
                  <div>
                    <p className="text-sm font-semibold text-amber-900 mb-1">{t('bulk_large_run_title', { count: missingCount.toLocaleString() })}</p>
                    <p className="text-xs text-amber-700 leading-relaxed">{t('bulk_large_run_detail')}</p>
                  </div>
                </div>
              </div>
            )}

            {/* Model strategy */}
            <div className="mx-6 mb-4">
              <p className="text-xs font-semibold text-slate-700 mb-2">{t('common_forecast_model')}</p>
              <div className="space-y-2">
                {([
                  { auto: true,  label: t('bulk_auto_select_best_model_per_cohort'), desc: t('bulk_analyses_each_cohort_s_history_independently') },
                  { auto: false, label: `Use ${currentModel} for all cohorts`, desc: null },
                ] as const).map(opt => (
                  <label key={String(opt.auto)} className={`flex items-start gap-3 cursor-pointer rounded-lg px-3 py-2 border transition-colors ${autoModel === opt.auto ? 'bg-[#e60000]/5 border-[#e60000]/20' : 'border-slate-100 hover:border-slate-200'}`}>
                    <input
                      type="radio"
                      checked={autoModel === opt.auto}
                      onChange={() => setAutoModel(opt.auto)}
                      className="mt-0.5 accent-[#e60000] shrink-0"
                    />
                    <div>
                      <span className={`text-xs font-medium ${autoModel === opt.auto ? 'text-slate-900' : 'text-slate-600'}`}>{opt.label}</span>
                      {opt.desc && <p className="text-[11px] text-slate-400 mt-0.5 leading-snug">{opt.desc}</p>}
                    </div>
                  </label>
                ))}
              </div>
            </div>

            {/* Confidence strategy */}
            <div className="mx-6 mb-5">
              <p className="text-xs font-semibold text-slate-700 mb-2">{t('bulk_confidence_band_width')}</p>
              <div className="space-y-2">
                {([
                  { auto: true,  label: t('bulk_auto_configure_confidence_per_cohort'), desc: t('bulk_sets_band_width_based_on_each_cohort_s_volati') },
                  { auto: false, label: t('bulk_use_current_settings_for_all_cohorts'), desc: null },
                ] as const).map(opt => (
                  <label key={String(opt.auto)} className={`flex items-start gap-3 cursor-pointer rounded-lg px-3 py-2 border transition-colors ${autoConfidence === opt.auto ? 'bg-[#e60000]/5 border-[#e60000]/20' : 'border-slate-100 hover:border-slate-200'}`}>
                    <input
                      type="radio"
                      checked={autoConfidence === opt.auto}
                      onChange={() => setAutoConfidence(opt.auto)}
                      className="mt-0.5 accent-[#e60000] shrink-0"
                    />
                    <div>
                      <span className={`text-xs font-medium ${autoConfidence === opt.auto ? 'text-slate-900' : 'text-slate-600'}`}>{opt.label}</span>
                      {opt.desc && <p className="text-[11px] text-slate-400 mt-0.5 leading-snug">{opt.desc}</p>}
                    </div>
                  </label>
                ))}
              </div>
            </div>

            {/* Parameters preview */}
            <div className="mx-6 mb-5 border border-slate-100 rounded-xl overflow-hidden">
              <div className="px-4 py-2.5 bg-slate-50 border-b border-slate-100">
                <p className="text-[11px] font-semibold text-slate-500 uppercase tracking-wide">
                  
                  {t('bulk_settings_to_be_applied_to_all')}{missingCount} remaining
                </p>
              </div>
              <div className="divide-y divide-slate-50">
                {[
                  { label: t('bulk_algorithm'), value: autoModel ? t('bulk_auto_selected_per_cohort') : currentModel },
                  { label: t('bulk_pre_horizon_z_score'), value: autoConfidence ? t('bulk_auto_configured_per_cohort') : `${params.preHorizonUncertainty}` },
                  { label: t('bulk_post_horizon_band_multiplier'), value: autoConfidence ? t('bulk_auto_configured_per_cohort') : `${params.postHorizonExpansionRate}×` },
                  { label: t('bulk_confidence_horizon'), value: autoConfidence ? t('bulk_auto_configured_per_cohort') : t('bulk_month', { p0: params.confidenceHorizon, p1: params.confidenceHorizon !== 1 ? 's' : '' }) },
                  { label: t('bulk_forecast_length'), value: `${params.forecastLength} months` },
                ].map(row => (
                  <div key={row.label} className="flex items-center justify-between px-4 py-2 text-xs">
                    <span className="text-slate-500">{row.label}</span>
                    <span className={`font-medium ${row.value.startsWith(t('bulk_auto')) ? 'text-[#e60000]' : 'text-slate-800'}`}>{row.value}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Run name + comment */}
            <div className="mx-6 mb-4 space-y-3">
              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1.5">{t('common_run_name')}{' '}<span className="font-normal text-slate-400">{t('bulk_optional')}</span>
                </label>
                <input
                  type="text"
                  value={runName}
                  onChange={e => setRunName(e.target.value)}
                  placeholder={t('bulk_bulk_run', { p0: new Date().toLocaleDateString() })}
                  className="w-full text-sm border border-slate-200 rounded-lg px-3 py-2.5 outline-none focus:ring-2 focus:ring-[#e60000]/20 focus:border-[#e60000]/40"
                />
              </div>
              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1.5">{t('common_comment')}{' '}<span className="font-normal text-slate-400">{t('bulk_optional')}</span>
                </label>
                <textarea
                  value={runComment}
                  onChange={e => setRunComment(e.target.value)}
                  placeholder={t('common_e_g_quarterly_pricing_review_updated_confiden')}
                  rows={2}
                  className="w-full text-sm border border-slate-200 rounded-lg px-3 py-2 outline-none focus:ring-2 focus:ring-[#e60000]/20 focus:border-[#e60000]/40 resize-none"
                />
              </div>
            </div>

            {/* Note */}
            <div className="mx-6 mb-5 flex items-start gap-2 text-xs text-amber-700 bg-amber-50 border border-amber-100 rounded-lg px-3 py-2.5">
              <AlertTriangle size={13} className="shrink-0 mt-0.5 text-amber-500" />
              <span>{t('bulk_combinations_that_already_have_a_saved_foreca')}</span>
            </div>

            </div>{/* end scrollable body */}

            {/* Actions */}
            <div className="flex items-center justify-end gap-3 px-6 py-4 bg-slate-50 border-t border-slate-100 shrink-0">
              <button
                onClick={handleClose}
                className="px-4 py-2 text-sm font-medium text-slate-600 hover:text-slate-800 transition-colors"
              >{t('bulk_skip_for_now')}</button>
              <button
                onClick={handleConfirm}
                className="px-5 py-2 bg-[#e60000] hover:bg-[#cc0000] text-white rounded-lg text-sm font-semibold transition-colors flex items-center gap-2"
              >
                <Zap size={14} />
                Generate {missingCount} Forecast{missingCount !== 1 ? 's' : ''}
              </button>
            </div>
          </>
        )}

        {/* ── Phase: Generating ── */}
        {phase === 'generating' && (
          <BulkGeneratingPanel progress={generationProgress} />
        )}

        {/* ── Phase: Complete ── */}
        {phase === 'complete' && summary && (
          <BulkCompletePanel
            grain={summary.grain ?? 'series'}
            generated={summary.generated}
            failed={summary.failed}
            skipped={summary.skipped}
            onClose={handleClose}
          />
        )}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Sub-panels (progress & summary are driven by context state in App.tsx,
// displayed via these presentational components)
// ---------------------------------------------------------------------------

function BulkGeneratingPanel({ progress }: { progress?: { current: number; total: number } }) {
  const { t } = useTranslation();
  const pct = progress && progress.total > 0
    ? Math.round((progress.current / progress.total) * 100)
    : 0;
  const showBar = progress && progress.total > 0;

  return (
    <div className="px-6 py-10 flex flex-col items-center text-center gap-5">
      <div className="w-14 h-14 rounded-full bg-slate-100 flex items-center justify-center">
        <Loader2 size={26} className="text-[#e60000] animate-spin" />
      </div>
      <div className="w-full max-w-xs">
        <h3 className="text-base font-semibold text-slate-900 mb-1">{showBar ? t('bulk_generating_forecasts') : t('bulk_preparing_forecasts')}</h3>
        {showBar ? (
          <>
            <p className="text-sm text-slate-500 mb-3">
              {progress!.current} of {progress!.total} cohorts complete
            </p>
            <div className="w-full bg-slate-100 rounded-full h-2.5 overflow-hidden">
              <div
                className="bg-[#e60000] h-2.5 rounded-full transition-all duration-300"
                style={{ width: `${pct}%` }}
              />
            </div>
            <p className="text-xs text-slate-400 mt-1.5">{pct}%</p>
          </>
        ) : (
          <p className="text-sm text-slate-500">{t('bulk_preparing_cohorts_enumerating_the_combination')}</p>
        )}
      </div>
    </div>
  );
}


function BulkCompletePanel({
  grain,
  generated,
  failed,
  skipped,
  onClose,
}: {
  grain: 'series' | 'leaves';
  generated: number;
  failed: number;
  skipped: SkippedCohort[];
  onClose: () => void;
}) {
  const { t } = useTranslation();
  // Everything the run could not cover, across BOTH populations. The heading
  // reads this rather than the run status: a run can finish cleanly and still
  // leave gaps, and that is the case the old heading hid.
  // A SCOPED run's `failed` and `skipped` are the SAME leaves - the worker
  // increments ibroFailed in the branch that pushes to skipped - so adding
  // them double-counts. Only a whole-book run reports two populations.
  const uncovered = grain === 'leaves' ? skipped.length : skipped.length + failed;
  // A skipped leaf is not a failure - the run did what it was asked. It IS a
  // coverage gap, and the panel stays amber rather than green because any
  // aggregate summed from these leaves is understated by exactly their
  // contribution, with nothing on screen to say so.
  const allSucceeded = failed === 0 && skipped.length === 0;

  return (
    <>
      <div className="px-6 py-8 flex flex-col items-center text-center gap-4">
        <div className={`w-14 h-14 rounded-full flex items-center justify-center ${allSucceeded ? 'bg-emerald-50' : 'bg-amber-50'}`}>
          <CheckCircle2 size={28} className={allSucceeded ? 'text-emerald-500' : 'text-amber-500'} />
        </div>

        <div>
          {/* A COVERAGE STATEMENT, not a success claim.
              "Bulk generation complete" was true of the RUN and misleading about
              the RESULT: it read as "everything is forecast" while leaves were
              missing. The run finishing and the book being covered are two
              different facts, and only one of them is what the user came to
              learn. When anything is uncovered the heading says so. */}
          <h3 className="text-lg font-bold text-slate-900 mb-3">
            {uncovered > 0
              ? t('bulk_complete_with_gaps', { count: uncovered })
              : t('bulk_complete_full_coverage')}
          </h3>

          {/* Result rows */}
          <div className="space-y-2 text-sm text-left max-w-xs mx-auto">
            {/* GRAIN IS STATED. This counter and the skipped list below come
                from DIFFERENT populations: `generated` counts chart series (the
                5-part Step 1 cohorts), `skipped` counts forecast leaves (the
                7-part keys the accuracy view and every aggregate are built
                from). They were previously stacked as though they were two
                views of one number, so "31,852 generated / 2 skipped" invited
                a subtraction that means nothing. */}
            <div className="flex items-center gap-3 bg-emerald-50 rounded-lg px-4 py-2.5">
              <CheckCircle2 size={15} className="text-emerald-500 shrink-0" />
              {/* The number stays BOLD and outside the string. Folding it
                  into the interpolation to add the grain lost the emphasis the
                  other rows in this panel use - the grain was the point, the
                  emphasis did not have to be the price. */}
              <span>
                <strong className="text-emerald-800">{generated}</strong>
                <span className="text-emerald-700"> {grain === 'leaves'
                  ? t('bulk_complete_leaves_generated')
                  : t('bulk_complete_series_generated')}</span>
              </span>
            </div>

            {/* The retirement rule, stated on screen rather than left to be
                discovered. A restored session's aggregate totals CHANGE when
                stored fit-on-aggregate entries stop being returned by the seam,
                and the standing principle is that a data issue is told to the
                user, not silently handled - including one we introduce. */}
            <div className="flex items-start gap-3 bg-slate-50 rounded-lg px-4 py-2.5">
              <Info size={15} className="text-slate-400 shrink-0 mt-0.5" />
              <span className="text-slate-600 text-[13px] leading-snug">{t('bulk_complete_retired')}</span>
            </div>

            {skipped.length > 0 && (
              <div className="bg-amber-50 rounded-lg px-4 py-2.5">
                <div className="flex items-center gap-3">
                  <AlertTriangle size={15} className="text-amber-500 shrink-0" />
                  <span>
                    <strong className="text-amber-800">{skipped.length}</strong>
                    <span className="text-amber-700"> {skipped.length === 1
                      ? t('bulk_complete_leaves_uncovered_one')
                      : t('bulk_complete_leaves_uncovered')}</span>
                  </span>
                </div>
                {/* NAMED, not counted. The count says an aggregate is
                    incomplete; only the key says which one, and by what. */}
                <ul className="mt-2 space-y-1 max-h-40 overflow-y-auto">
                  {skipped.map(sk => (
                    <li key={sk.fKey} className="text-[11px] leading-snug text-amber-800">
                      <span className="font-mono">{sk.fKey.split('|').join(' \u00b7 ')}</span>
                      <span className="text-amber-600"> {'\u2014'} {t(SKIP_REASON_KEY[sk.reason])}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* ONE SKIP VOCABULARY. This row and the leaf list above both used
                the word "skipped" for different populations at different
                grains, which made the modal read as though a leaf skip and a
                series skip were the same event counted twice. Both now say
                "could not be forecast", and each names its own grain. The
                reason wording comes from SKIP_REASON_KEY in both places, so
                there is one enum behind the whole panel. */}
            {grain !== 'leaves' && failed > 0 && (
              <div className="flex items-center gap-3 bg-amber-50 rounded-lg px-4 py-2.5">
                <AlertTriangle size={15} className="text-amber-500 shrink-0" />
                <span>
                  <strong className="text-amber-800">{failed}</strong>
                  <span className="text-amber-700"> {t('bulk_complete_series_uncovered')}</span>
                </span>
              </div>
            )}
          </div>
        </div>
      </div>

      <div className="flex justify-end px-6 py-4 bg-slate-50 border-t border-slate-100">
        <button
          onClick={onClose}
          className="px-5 py-2 bg-slate-800 hover:bg-slate-900 text-white rounded-lg text-sm font-semibold transition-colors"
        >{t('bulk_done')}</button>
      </div>
    </>
  );
}
