import React, { useState } from 'react';
import { CheckCircle2, Zap, X, AlertTriangle, Loader2 } from 'lucide-react';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface ForecastParams {
  preHorizonUncertainty: number;
  postHorizonExpansionRate: number;
  confidenceHorizon: number;
  forecastLength: number;
}

interface CohortLabel {
  segment: string;
  product: string;
  channel: string;
  scenario: string;
}

export interface BulkGenerateModalProps {
  /** Controls visibility */
  isOpen: boolean;
  /** Fired when the modal should close (cancel or Done) */
  onClose: () => void;
  /** The combination that was just explicitly generated by the user */
  sourceCohort: CohortLabel | null;
  /** Total count of dim-combinations that currently have no forecast */
  missingCount: number;
  /** HW parameters that will be used for all generated forecasts */
  params: ForecastParams;
  /**
   * Called when the user confirms.  Runs bulk generation and resolves with:
   *   generated — forecasts successfully written
   *   failed    — combos skipped due to insufficient data
   */
  onConfirm: (opts: { name: string; comment: string }) => Promise<{ generated: number; failed: number }>;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

type Phase = 'confirm' | 'generating' | 'complete';

export function BulkGenerateModal({
  isOpen,
  onClose,
  sourceCohort,
  missingCount,
  params,
  onConfirm,
}: BulkGenerateModalProps) {
  const [phase, setPhase] = useState<Phase>('confirm');
  const [summary, setSummary] = useState<{ generated: number; failed: number } | null>(null);
  const [runName, setRunName] = useState('');
  const [runComment, setRunComment] = useState('');

  if (!isOpen) return null;

  // Reset when re-opened
  const handleClose = () => {
    setPhase('confirm');
    setSummary(null);
    setRunName('');
    setRunComment('');
    onClose();
  };

  const handleConfirm = async () => {
    setPhase('generating');
    try {
      const result = await onConfirm({ name: runName.trim(), comment: runComment.trim() });
      setSummary(result);
      setPhase('complete');
    } catch {
      setPhase('complete');
      setSummary({ generated: 0, failed: missingCount });
    }
  };

  // Cohort label string
  const cohortStr = sourceCohort
    ? [sourceCohort.segment, sourceCohort.product, sourceCohort.channel]
        .filter(v => v && v !== 'All')
        .join(' · ') || 'All cohorts'
    : null;

  return (
    /* Backdrop */
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={phase === 'generating' ? undefined : handleClose} />

      {/* Modal card */}
      <div className="relative w-full max-w-lg mx-4 bg-white rounded-2xl shadow-2xl overflow-hidden">

        {/* ── Phase: Confirm ── */}
        {phase === 'confirm' && (
          <>
            {/* Header */}
            <div className="flex items-start justify-between px-6 pt-6 pb-4">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-[#e60000]/10 flex items-center justify-center shrink-0">
                  <Zap size={20} className="text-[#e60000]" />
                </div>
                <div>
                  <h2 className="text-base font-bold text-slate-900">Apply to All Remaining Combinations?</h2>
                  <p className="text-xs text-slate-500 mt-0.5">
                    {missingCount} combination{missingCount !== 1 ? 's' : ''} {missingCount !== 1 ? 'don\'t' : 'doesn\'t'} have a forecast yet
                  </p>
                </div>
              </div>
              <button onClick={handleClose} className="text-slate-400 hover:text-slate-600 transition-colors p-1">
                <X size={18} />
              </button>
            </div>

            {/* Source cohort pill */}
            {cohortStr && (
              <div className="px-6 pb-3">
                <div className="bg-slate-50 rounded-lg px-4 py-2.5 text-xs flex items-center gap-2">
                  <span className="text-slate-400">Just generated:</span>
                  <span className="font-semibold text-slate-700">{cohortStr}</span>
                  <span className="text-slate-400 ml-1">· {sourceCohort?.scenario}</span>
                </div>
              </div>
            )}

            {/* Parameters preview */}
            <div className="mx-6 mb-5 border border-slate-100 rounded-xl overflow-hidden">
              <div className="px-4 py-2.5 bg-slate-50 border-b border-slate-100">
                <p className="text-[11px] font-semibold text-slate-500 uppercase tracking-wide">
                  Settings to be applied to all {missingCount} remaining
                </p>
              </div>
              <div className="divide-y divide-slate-50">
                {[
                  { label: 'Algorithm', value: 'Exponential smoothing (see model selector)' },
                  { label: 'Pre-Horizon z-score', value: `${params.preHorizonUncertainty}` },
                  { label: 'Post-Horizon Band Multiplier', value: `${params.postHorizonExpansionRate}×` },
                  { label: 'Confidence Horizon', value: `${params.confidenceHorizon} month${params.confidenceHorizon !== 1 ? 's' : ''}` },
                  { label: 'Forecast Length', value: `${params.forecastLength} months` },
                ].map(row => (
                  <div key={row.label} className="flex items-center justify-between px-4 py-2 text-xs">
                    <span className="text-slate-500">{row.label}</span>
                    <span className="font-medium text-slate-800">{row.value}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Run name + comment */}
            <div className="mx-6 mb-4 space-y-3">
              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1.5">
                  Run Name <span className="font-normal text-slate-400">(optional)</span>
                </label>
                <input
                  type="text"
                  value={runName}
                  onChange={e => setRunName(e.target.value)}
                  placeholder={`Bulk Run — ${new Date().toLocaleDateString()}`}
                  className="w-full text-sm border border-slate-200 rounded-lg px-3 py-2.5 outline-none focus:ring-2 focus:ring-[#e60000]/20 focus:border-[#e60000]/40"
                />
              </div>
              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1.5">
                  Comment <span className="font-normal text-slate-400">(optional)</span>
                </label>
                <textarea
                  value={runComment}
                  onChange={e => setRunComment(e.target.value)}
                  placeholder="e.g. Quarterly pricing review, updated confidence settings…"
                  rows={2}
                  className="w-full text-sm border border-slate-200 rounded-lg px-3 py-2 outline-none focus:ring-2 focus:ring-[#e60000]/20 focus:border-[#e60000]/40 resize-none"
                />
              </div>
            </div>

            {/* Note */}
            <div className="mx-6 mb-5 flex items-start gap-2 text-xs text-amber-700 bg-amber-50 border border-amber-100 rounded-lg px-3 py-2.5">
              <AlertTriangle size={13} className="shrink-0 mt-0.5 text-amber-500" />
              <span>
                Combinations that already have a saved forecast will be skipped.
                Combinations with fewer than 4 data points cannot be forecast and will also be skipped.
              </span>
            </div>

            {/* Actions */}
            <div className="flex items-center justify-end gap-3 px-6 py-4 bg-slate-50 border-t border-slate-100">
              <button
                onClick={handleClose}
                className="px-4 py-2 text-sm font-medium text-slate-600 hover:text-slate-800 transition-colors"
              >
                Skip for now
              </button>
              <button
                onClick={handleConfirm}
                className="px-5 py-2 bg-[#e60000] hover:bg-[#cc0000] text-white rounded-lg text-sm font-semibold transition-colors flex items-center gap-2"
              >
                <Zap size={14} />
                Generate {missingCount} Forecast{missingCount !== 1 ? 's' : ''}
              </button>
            </div>
          </>
        )}

        {/* ── Phase: Generating ── */}
        {phase === 'generating' && (
          <BulkGeneratingPanel />
        )}

        {/* ── Phase: Complete ── */}
        {phase === 'complete' && summary && (
          <BulkCompletePanel
            generated={summary.generated}
            failed={summary.failed}
            onClose={handleClose}
          />
        )}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Sub-panels (progress & summary are driven by context state in App.tsx,
// displayed via these presentational components)
// ---------------------------------------------------------------------------

function BulkGeneratingPanel() {
  return (
    <div className="px-6 py-10 flex flex-col items-center text-center gap-5">
      <div className="w-14 h-14 rounded-full bg-slate-100 flex items-center justify-center">
        <Loader2 size={26} className="text-[#e60000] animate-spin" />
      </div>
      <div>
        <h3 className="text-base font-semibold text-slate-900 mb-1">Generating forecasts…</h3>
        <p className="text-sm text-slate-500">
          Running forecasts for each combination. This may take a few seconds.
        </p>
      </div>
    </div>
  );
}

function BulkCompletePanel({
  generated,
  failed,
  onClose,
}: {
  generated: number;
  failed: number;
  onClose: () => void;
}) {
  const allSucceeded = failed === 0;

  return (
    <>
      <div className="px-6 py-8 flex flex-col items-center text-center gap-4">
        <div className={`w-14 h-14 rounded-full flex items-center justify-center ${allSucceeded ? 'bg-emerald-50' : 'bg-amber-50'}`}>
          <CheckCircle2 size={28} className={allSucceeded ? 'text-emerald-500' : 'text-amber-500'} />
        </div>

        <div>
          <h3 className="text-lg font-bold text-slate-900 mb-3">Bulk Generation Complete</h3>

          {/* Result rows */}
          <div className="space-y-2 text-sm text-left max-w-xs mx-auto">
            <div className="flex items-center gap-3 bg-emerald-50 rounded-lg px-4 py-2.5">
              <CheckCircle2 size={15} className="text-emerald-500 shrink-0" />
              <span>
                <strong className="text-emerald-800">{generated}</strong>
                <span className="text-emerald-700"> forecast{generated !== 1 ? 's' : ''} generated successfully</span>
              </span>
            </div>

            {failed > 0 && (
              <div className="flex items-center gap-3 bg-amber-50 rounded-lg px-4 py-2.5">
                <AlertTriangle size={15} className="text-amber-500 shrink-0" />
                <span>
                  <strong className="text-amber-800">{failed}</strong>
                  <span className="text-amber-700"> skipped — insufficient data points</span>
                </span>
              </div>
            )}
          </div>
        </div>
      </div>

      <div className="flex justify-end px-6 py-4 bg-slate-50 border-t border-slate-100">
        <button
          onClick={onClose}
          className="px-5 py-2 bg-slate-800 hover:bg-slate-900 text-white rounded-lg text-sm font-semibold transition-colors"
        >
          Done
        </button>
      </div>
    </>
  );
}
