import React, { createContext, useContext } from 'react';
import type { BaseForecast, MarketEventAdjustedForecast, BulkRunRecord , SkipReason } from '../types/forecast';

interface ForecastContextValue {
  /** Typed Holt-Winters output for Inflow/Retention/Outflow (new engine). */
  baseForecast: BaseForecast | null;
  setBaseForecast: (f: BaseForecast | null) => void;
  /** Baseline extended with market-event adjustments. */
  adjustedForecast: MarketEventAdjustedForecast | null;
  setAdjustedForecast: (f: MarketEventAdjustedForecast | null) => void;
  /**
   * All typed BaseForecast objects keyed by `${segment}|${product}|${channel}`.
   * Contains manually-generated AND bulk-generated forecasts.
   * Used by ForecastVsActualsTab to compute MAPE across multiple cohorts.
   */
  forecastStore: Map<string, BaseForecast>;
  setForecastStore: (fn: (prev: Map<string, BaseForecast>) => Map<string, BaseForecast>) => void;
  /**
   * THE seam. Resolve a forecast by key: stored fit, or derived from the leaves
   * in scope, or null with the reason.
   *
   * Every reader goes through this rather than reading `forecastStore` directly.
   * A bare `forecastStore.get` answers "is it stored", which stopped being the
   * question the moment aggregates became derivable - and answering the wrong
   * question is how a cohort came to show a previous cohort's forecast.
   */
  resolveForecast: (key: string) => { forecast: BaseForecast | null; reason: SkipReason | null };
  /** Can a key produce a forecast at all - stored OR derivable? Does not derive. */
  canResolve: (key: string) => boolean;
  /**
   * True when at least one baseline forecast exists.
   * Combines the new typed state with the legacy savedForecasts dictionary
   * so step-locking works before the internals are fully migrated.
   */
  hasBaseline: boolean;
  /** ISO timestamp string set whenever a new BaseForecast is saved. */
  updatedAt: string | null;
  /** Ordered history of all bulk generation runs. */
  bulkRuns: BulkRunRecord[];
  setBulkRuns: (runs: BulkRunRecord[] | ((prev: BulkRunRecord[]) => BulkRunRecord[])) => void;
}

const ForecastContext = createContext<ForecastContextValue | null>(null);

export function useForecast(): ForecastContextValue {
  const ctx = useContext(ForecastContext);
  if (!ctx) throw new Error('useForecast must be used within ForecastProvider');
  return ctx;
}

interface ForecastProviderProps {
  children: React.ReactNode;
  /** State is owned by App.tsx so that handlers in App can write to the context. */
  baseForecast: BaseForecast | null;
  setBaseForecast: (f: BaseForecast | null) => void;
  adjustedForecast: MarketEventAdjustedForecast | null;
  setAdjustedForecast: (f: MarketEventAdjustedForecast | null) => void;
  forecastStore: Map<string, BaseForecast>;
  setForecastStore: (fn: (prev: Map<string, BaseForecast>) => Map<string, BaseForecast>) => void;
  resolveForecast: (key: string) => { forecast: BaseForecast | null; reason: SkipReason | null };
  canResolve: (key: string) => boolean;
  /**
   * Passed from App so that the legacy savedForecasts record (generated by the
   * existing HW engine) also satisfies the "baseline saved" check while the
   * internals of each step are migrated incrementally.
   */
  hasLegacyBaseline: boolean;
  /** Set to an ISO timestamp string whenever a new BaseForecast is written. */
  updatedAt: string | null;
  bulkRuns: BulkRunRecord[];
  setBulkRuns: (runs: BulkRunRecord[] | ((prev: BulkRunRecord[]) => BulkRunRecord[])) => void;
}

export function ForecastProvider({
  children,
  baseForecast,
  setBaseForecast,
  adjustedForecast,
  setAdjustedForecast,
  forecastStore,
  setForecastStore,
  resolveForecast,
  canResolve,
  hasLegacyBaseline,
  updatedAt,
  bulkRuns,
  setBulkRuns,
}: ForecastProviderProps) {
  const hasBaseline = baseForecast !== null || hasLegacyBaseline;

  return (
    <ForecastContext.Provider
      value={{ baseForecast, setBaseForecast, adjustedForecast, setAdjustedForecast, forecastStore, setForecastStore, resolveForecast, canResolve, hasBaseline, updatedAt, bulkRuns, setBulkRuns }}
    >
      {children}
    </ForecastContext.Provider>
  );
}
